name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Golang Pieline
      # You may pin to the exact commit or the version.
      # uses: shoukoo/golang-pipeline@e056a6791721d91d11f5247e881bc1c4c6f7f46c
      uses: shoukoo/golang-pipeline@0.2.0    

#    - name: configure
#      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
