name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0

    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.18.0
        # Path to the go.mod or go.work file.
        #go-version-file: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: true
        # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
        #architecture: # optional      

#    - name: configure
#      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
