name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0

    - name: Typescript compiler
      # You may pin to the exact commit or the version.
      # uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069
      uses: iCrawl/action-tsc@v1

    - name: Golang Action
      # You may pin to the exact commit or the version.
      # uses: cedrickring/golang-action@382e630a8e1ec81acc05518fdd4498a7c2a68ba6
      uses: cedrickring/golang-action@1.18.0    

#    - name: configure
#      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
